version: '3.9'
services:
  web:
    container_name: django_app
    build:
      context: .
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py migrate && 
      python manage.py runserver 0.0.0.0:8000 &&
      celery worker -A MyShop -l INFO"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
        db:
            condition: service_healthy

  db:
    container_name: db_container
    image: postgres:latest
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres123"
      POSTGRES_DB: "ShopDB"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped


  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "example@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres123"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - db

  rabbitmq:
    image: rabbitmq:3.13.0-management
    container_name: rabbitmq_container
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    depends_on:
      - web

  celery:
    build:
      context: .
    container_name: celery_container
    command: celery -A MyShop worker -l INFO
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - web
      - rabbitmq

  flower:
    build:
      context: .
    container_name: flower_container
    command: celery -A MyShop flower
    env_file:
      - ./.env
    ports:
      - "5555:5555"
    depends_on:
      - web
      - celery
      - rabbitmq

volumes:
  postgres_data:
  pgadmin-data:
  rabbitmq: